=== renanrcrr/gaadt-cm/src/gaadt/xml/mapa.dtd
<!ELEMENT mapa (conceitoontologia*, conceito+, exemplo*, legenda*, fraselivre*, frasecontextualizada*, arco+, bezier*)>
	<!ATTLIST mapa tipomapa NMTOKEN #REQUIRED>
	<!ATTLIST mapa autor CDATA #IMPLIED>
<!ELEMENT conceitoontologia EMPTY>
	<!ATTLIST conceitoontologia texto CDATA #REQUIRED>
<!ELEMENT conceito EMPTY>
	<!ATTLIST conceito id ID #REQUIRED>
	<!ATTLIST conceito texto CDATA #REQUIRED>
	<!ATTLIST conceito x NMTOKEN #REQUIRED>
	<!ATTLIST conceito y NMTOKEN #REQUIRED>
	<!ATTLIST conceito corborda NMTOKEN #IMPLIED>
	<!ATTLIST conceito corpreenchimento NMTOKEN #IMPLIED>
	<!ATTLIST conceito nomeletra CDATA #IMPLIED>
	<!ATTLIST conceito estiloletra NMTOKEN #IMPLIED>
	<!ATTLIST conceito tamanholetra NMTOKEN #IMPLIED>
	<!ATTLIST conceito corletra NMTOKEN #IMPLIED>
	<!ATTLIST conceito anexotexto CDATA #IMPLIED>
	<!ATTLIST conceito anexohtml CDATA #IMPLIED>
<!ELEMENT exemplo EMPTY>
	<!ATTLIST exemplo id ID #REQUIRED>
	<!ATTLIST exemplo texto CDATA #REQUIRED>
	<!ATTLIST exemplo x NMTOKEN #REQUIRED>
	<!ATTLIST exemplo y NMTOKEN #REQUIRED>
	<!ATTLIST exemplo corborda NMTOKEN #IMPLIED>
	<!ATTLIST exemplo corpreenchimento NMTOKEN #IMPLIED>
	<!ATTLIST exemplo nomeletra CDATA #IMPLIED>
	<!ATTLIST exemplo estiloletra NMTOKEN #IMPLIED>
	<!ATTLIST exemplo tamanholetra NMTOKEN #IMPLIED>
	<!ATTLIST exemplo corletra NMTOKEN #IMPLIED>
	<!ATTLIST exemplo anexotexto CDATA #IMPLIED>
	<!ATTLIST exemplo anexohtml CDATA #IMPLIED>
<!ELEMENT legenda EMPTY>
	<!ATTLIST legenda texto CDATA #REQUIRED>
	<!ATTLIST legenda x NMTOKEN #REQUIRED>
	<!ATTLIST legenda y NMTOKEN #REQUIRED>
	<!ATTLIST legenda nomeletra CDATA #IMPLIED>
	<!ATTLIST legenda estiloletra NMTOKEN #IMPLIED>
	<!ATTLIST legenda tamanholetra NMTOKEN #IMPLIED>
	<!ATTLIST legenda corletra NMTOKEN #IMPLIED>
<!ELEMENT fraselivre EMPTY>
	<!ATTLIST fraselivre id ID #REQUIRED>
	<!ATTLIST fraselivre texto CDATA #REQUIRED>
	<!ATTLIST fraselivre x NMTOKEN #REQUIRED>
	<!ATTLIST fraselivre y NMTOKEN #REQUIRED>
	<!ATTLIST fraselivre nomeletra CDATA #IMPLIED>
	<!ATTLIST fraselivre estiloletra NMTOKEN #IMPLIED>
	<!ATTLIST fraselivre tamanholetra NMTOKEN #IMPLIED>
	<!ATTLIST fraselivre corletra NMTOKEN #IMPLIED>
<!ELEMENT frasecontextualizada EMPTY>
	<!ATTLIST frasecontextualizada id ID #REQUIRED>
	<!ATTLIST frasecontextualizada texto CDATA #REQUIRED>
	<!ATTLIST frasecontextualizada supertipo CDATA #REQUIRED>
	<!ATTLIST frasecontextualizada x NMTOKEN #REQUIRED>
	<!ATTLIST frasecontextualizada y NMTOKEN #REQUIRED>
	<!ATTLIST frasecontextualizada nomeletra CDATA #IMPLIED>
	<!ATTLIST frasecontextualizada estiloletra NMTOKEN #IMPLIED>
	<!ATTLIST frasecontextualizada tamanholetra NMTOKEN #IMPLIED>
	<!ATTLIST frasecontextualizada corletra NMTOKEN #IMPLIED>
<!ELEMENT arco EMPTY>
	<!ATTLIST arco tipo NMTOKEN #REQUIRED>
	<!ATTLIST arco origem IDREF #REQUIRED>
	<!ATTLIST arco alvo IDREF #REQUIRED>
	<!ATTLIST arco corlinha NMTOKEN #IMPLIED>
<!ELEMENT bezier EMPTY>
	<!ATTLIST arco tipo NMTOKEN #REQUIRED>
	<!ATTLIST arco x NMTOKEN #REQUIRED>
	<!ATTLIST arco y NMTOKEN #REQUIRED>
	<!ATTLIST arco origem IDREF #REQUIRED>
	<!ATTLIST arco alvo IDREF #REQUIRED>
	<!ATTLIST arco corlinha NMTOKEN #IMPLIED>

=== renanrcrr/gaadt-cm/src/gaadt/xml/mapa_celula.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapa SYSTEM "mapa.dtd">

<mapa tipomapa="1">

<conceitoontologia texto="Membrana nuclear"/>
<conceitoontologia texto="Membrana"/>
<conceitoontologia texto="Poro"/>

<conceito id="0" texto="Núcleo" x="499.0" y="122.0" corborda="-16777216" corpreenchimento="-1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<conceito id="1" texto="Mitocondrias" x="707.0" y="422.0" corborda="-16777216" corpreenchimento="-1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<conceito id="2" texto="Centríolos" x="794.0" y="322.0" corborda="-16777216" corpreenchimento="-1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<conceito id="3" texto="Cromatina" x="341.0" y="286.0" corborda="-16777216" corpreenchimento="-1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<conceito id="4" texto="Célula" x="540.0" y="383.0" corborda="-16777216" corpreenchimento="-1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />

<frasecontextualizada id="5" texto="usa" supertipo="assimetria.processo.entrada.sentido_direto" x="686.25" y="334.0" tiposeta="0" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<frasecontextualizada id="6" texto="contém" supertipo="assimetria.partição.física.sentido_direto" x="549.0" y="461.0" tiposeta="1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<frasecontextualizada id="7" texto="é componente de" supertipo="assimetria.partição.temporalidade.sentido_inverso" x="534.25" y="234.0" tiposeta="0" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<frasecontextualizada id="8" texto="é delimitado por" supertipo="assimetria.definição.definidor.sentido_inverso" x="381.75" y="169.5" tiposeta="0" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />
<frasecontextualizada id="9" texto="tem atributo" supertipo="assimetria.caracterização.sentido_direto" x="386.0" y="377.0" tiposeta="1" nomeletra="Dialog.plain" estiloletra="0" tamanholetra="12" corletra="-16777216" />

<arco tipo="0" origem="0" alvo="8" corlinha="-16776961" estilo="1" />
<arco tipo="0" origem="7" alvo="4" corlinha="-16776961" estilo="1" />
<arco tipo="1" origem="9" alvo="3" corlinha="-16776961" estilo="1" />
<arco tipo="0" origem="5" alvo="2" corlinha="-16776961" estilo="1" />
<arco tipo="1" origem="6" alvo="1" corlinha="-16776961" estilo="1" />
<arco tipo="0" origem="8" alvo="3" corlinha="-16776961" estilo="1" />
<arco tipo="0" origem="4" alvo="5" corlinha="-16776961" estilo="1" />
<arco tipo="1" origem="4" alvo="9" corlinha="-16776961" estilo="1" />
<arco tipo="1" origem="4" alvo="6" corlinha="-16776961" estilo="1" />
<arco tipo="0" origem="0" alvo="7" corlinha="-16776961" estilo="1" />

</mapa>
