=== renanrcrr/gaadt-cm/src/gaadt/xml/Taxonomia.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT frase (#PCDATA)>

<!ELEMENT desc (#PCDATA)>

<!ELEMENT supertipo (desc? , (frase+ | supertipo+ ) )>
<!ATTLIST supertipo
    valor CDATA #IMPLIED
  >

<!ELEMENT taxonomia (supertipo)+>
<!ATTLIST taxonomia
    versao CDATA #IMPLIED
  >

=== renanrcrr/gaadt-cm/src/gaadt/xml/taxonomia.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE taxonomia SYSTEM "c:/wamp/www/cmeditor/repositorio/Taxonomia.dtd"> 
<taxonomia versao="1.0">
	<supertipo valor="assimetria">
		<desc>A dimensão de assimetria representa a relação semântica entre dois conceitos na qual a mudança da ordem de leitura dos conceitos resulta em alteração substancial no sentido da proposição. Por exemplo, dada a proposição "CASA possui JANELA", se alterarmos a posição dos conceitos, a proposição resultante "JANELA possui CASA" não mantém o sentido inicial. A dimensão de simetria, por outro lado, representa a relação semântica entre conceitos na qual o significado da proposição é mantido caso haja mudança na posição dos conceitos.</desc>
		<supertipo valor="processo">
			<desc>Esta dimensão representa a ligação semântica existente entre conceitos envolvidos em um processo. Um processo utiliza entradas e gera saídas através de alguma transformação. Por exemplo, na proposição "VAPOR é transformado em CHUVA", o conceito VAPOR é a entrada do processo e o conceito CHUVA é a saída do processo. A transformação (no caso, o fenômeno da condensação) não é mencionada no exemplo dado. A dimensão de processo possui subdimensões que representam as possíveis ligações entre conceitos.</desc>
			<supertipo valor="entrada">
				<desc>A dimensão "entrada" representa a ligação semântica que existe entre conceitos na qual um conceito é entrada de um processo. Assim, por exemplo, na proposição "CONDENSAÇÃO utiliza VAPOR", o conceito CONDENSAÇÃO representa o processo em si, enquanto o conceito VAPOR representa a entrada para o processo.</desc>                                        
                                <supertipo valor="sentido_direto">
                                        <desc>Descrição do supertipo</desc>   
					<frase>usa</frase>
					<frase>usa como entrada</frase>
					<frase>utiliza</frase>
					<frase>utiliza como entrada</frase>
					<frase>transforma</frase>
					<frase>converte</frase>
					<frase>altera</frase>
					<frase>modifica</frase>
					<frase>faz uso de</frase>
			</supertipo>
				<supertipo valor="sentido_inverso">
                                        <desc>Descrição do supertipo</desc>   
					<frase>é entrada de</frase>
					<frase>é usado por</frase>
					<frase>é utilizado por</frase>
					<frase>é transformado por</frase>
					<frase>é convertido por</frase>
					<frase>é alterado por</frase>
					<frase>é modificado por</frase>
					<frase>é mutado por</frase>
				</supertipo>
			</supertipo>
			<supertipo valor="saída">
				<desc>A dimensão "saída" representa a ligação existente entre conceitos na qual um dos conceitos representa a saída, ou seja, o produto de um processo. Por exemplo, dada a proposição "CONDENSAÇÃO gera CHUVA", o conceito CONDENSAÇÃO representa o processo em si, enquanto o conceito CHUVA representa a saída do processo.</desc>
				<supertipo valor="sentido_direto">
                                        <desc>Descrição do supertipo</desc>   
					<frase>gera</frase>
					<frase>causa</frase>
					<frase>produz</frase>
					<frase>provoca</frase>
					<frase>resulta em</frase>
					<frase>tem como resultado</frase>
					<frase>forma</frase>
					<frase>tem como conseqüência</frase>
					<frase>tem como saída</frase>
				</supertipo>
				<supertipo valor="sentido_inverso">
                                        <desc>Descrição do supertipo</desc>   
					<frase>é gerado por</frase>
					<frase>é causado por</frase>
					<frase>é produzido por</frase>
					<frase>é provocado por</frase>
					<frase>é resultado de</frase>
					<frase>é formado por</frase>
					<frase>é conseqüência de</frase>
					<frase>é saída de</frase>
				</supertipo>
			</supertipo>
			<supertipo valor="transformação">
				<desc>Esta dimensão representa a ligação existente entre dois conceitos na qual um conceito é uma entrada de um processo e o outro conceito é uma saída do processo. Neste tipo de proposição, o processo não é explicitamente mencionado. Por exemplo, na proposição "TRIGO é transformado em PÃO", os conceitos TRIGO e PÃO estão ligados por uma frase de ligação da dimensão de transformação. Esta dimensão possui duas subdimensões, dependendo de como o processo é controlado.</desc>
				<supertipo valor="controle_interno">
					<desc>Esta dimensão representa a ligação entre dois conceitos em que um dos conceitos é a entrada e o outro é a saída de um processo. Adicionalmente, esta dimensão representa que o processo é regulado/controlado pelo conceito de entrada, ou seja, não há uma entidade externa que efetive este controle. Por exemplo, na proposição "LAGARTA converte-se em BORBOLETA", os conceitos LAGARTA e BORBOLETA representam, respectivamente, a entrada e a saída do processo. Adicionalmente, este processo é controlado por um dos conceitos (no caso, LAGARTA).</desc>
					<supertipo valor="sentido_direto">
                                                <desc>Descrição do supertipo</desc>   
						<frase>transforma-se em</frase>
						<frase>converte-se em</frase>
						<frase>modifica-se para</frase>
						<frase>altera-se para</frase>
						<frase>muta-se em</frase>
					</supertipo>
					<supertipo valor="sentido_inverso">
                                                <desc>Descrição do supertipo</desc>   
						<frase>provém de</frase>
						<frase>surge de</frase>
						<frase>tem como origem</frase>
						<frase>resulta de</frase>
						<frase>é conseqüência de</frase>
						<frase>é alteração de</frase>
						<frase>é transformação de</frase>
						<frase>é conversão de</frase>
						<frase>é mutação de</frase>
						<frase>é modificação de</frase>
					</supertipo>
				</supertipo>
				<supertipo valor="controle_interno">
					<desc>Esta dimensão representa a ligação entre conceitos que representam a entrada e a saída de um processo. Adicionalmente, este processo é regulado/controlado/disparado por uma entidade externa. Assim, por exemplo, a proposição "TRIGO é transformado em PÃO", os conceitos TRIGO e PÃO são a entrada e a saída do processo de cozimento, que é disparado por uma entidade externa (o cozinheiro, no caso).</desc>
					<supertipo valor="sentido_direto">
                                                <desc>Descrição do supertipo</desc>   
						<frase>é transformado em</frase>
						<frase>é convertido em</frase>
						<frase>é alterado em</frase>
						<frase>é mutado em</frase>
						<frase>é modificado em</frase>
						<frase>resulta em</frase>
						<frase>tem como conseqüência</frase>
					</supertipo>
					<supertipo valor="sentido_inverso">
                                                <desc>Descrição do supertipo</desc>   
						<frase>provém de</frase>
						<frase>surge de</frase>
						<frase>tem como origem</frase>
						<frase>resulta de</frase>
						<frase>é conseqüência de</frase>
						<frase>é alteração de</frase>
						<frase>é transformação de</frase>
						<frase>é conversão de</frase>
						<frase>é mutação de</frase>
						<frase>é modificação de</frase>
					</supertipo>
				</supertipo>
			</supertipo>
		</supertipo>
		<supertipo valor="temporalidade">
                    <desc>Esta dimensão representa a ligação semântica entre conceitos na qual se deseja expressar o sentido de temporalidade, ou seja, na qual dois conceitos são ordenados/comparados em relação ao tempo. Assim, as proposições "EVAPORAÇÃO precede CONDENSAÇÃO", "UM MÊS é mais longo que UMA SEMANA" e "CURSO dura UM MÊS", são exemplos de uso da dimensão temporal. Observa-se que, nestes casos, a mudança da ordem de leitura dos conceitos altera o sentido da frase. Por esta razão, esta dimensão encontra-se classificada sob a dimensão de assimetria. Por outro lado, há uma outra dimensão de temporalidade, classificada sob a dimensão de simetria, para os casos em que a mudança da ordem dos conceitos não influencia no sentido da proposição.</desc>
			<supertipo valor="ordenação">
				<desc>A dimensão de ordenação representa a ligação que existe entre conceitos quando tais conceitos são ordenados no tempo, ou seja, quando se deseja expressar que um conceito existiu/ocorreu/persistiu em um momento anterior a outro. Assim, por exemplo, a proposição "OUTUBRO sucede SETEMBRO" usa uma frase de ligação desta dimensão. Nesta proposição, os conceitos encontram-se ordenados no tempo.</desc>
				<supertipo valor="sentido_direto">
                                        <desc>Descrição do supertipo</desc>   
					<frase>precede</frase>
					<frase>antecede</frase>
					<frase>ocorre antes de</frase>
					<frase>é anterior a</frase>
					<frase>é primeiro que</frase>
					<frase>existe antes que</frase>
					<frase>é antes de</frase>
					<frase>é sucedido por</frase>
				</supertipo>
				<supertipo valor="sentido_inverso">
                                        <desc>Descrição do supertipo</desc>   
					<frase>é precedido por</frase>
					<frase>é antecedido por</frase>
					<frase>sucede</frase>
					<frase>segue</frase>
					<frase>é posterior que</frase>
					<frase>ocorre depois de</frase>
					<frase>existe depois que</frase>
					<frase>é depois de</frase>
				</supertipo>
			</supertipo>
			<supertipo valor="comparação">
				<desc>Esta dimensão representa a ligação semântica entre dois conceitos na qual se compara a duração de um conceito em relação à duração do outro. Por exemplo, na proposição "MARÇO é mais longo que FEVEREIRO", os dois conceitos são comparados com relação a suas respectivas durabilidades.</desc>
				<supertipo valor="sentido_direto">
                                        <desc>Descrição do supertipo</desc>   
					<frase>é mais longo que</frase>
					<frase>é maior que</frase>
					<frase>leva mais tempo que</frase>
					<frase>é mais duradouro que</frase>
					<frase>dura mais tempo que</frase>
				</supertipo>
				<supertipo valor="sentido_inverso">
                                        <desc>Descrição do supertipo</desc>
